<<<<<<< HEAD
# Generated by rspec-sinatra. (2016-06-14 11:00:10 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'app.rb')
=======
# Generated by rspec-sinatra. (2016-06-14 09:22:33 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '../app/', 'app.rb')
>>>>>>> b35914ebd2f96793a533e3c5c5c80210e9b67766

require 'capybara'
require 'capybara/rspec'
require 'rspec'
<<<<<<< HEAD
require 'database_cleaner'
require_relative 'helpers/session'

Capybara.app = Bookmarks

RSpec.configure do |config|

  config.include SessionHelpers
  config.include Capybara::DSL

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end

RSpec.configure do |config|

=======
require './app/models/link'
require 'database_cleaner'

Capybara.app = BookmarkManager

RSpec.configure do |config|
>>>>>>> b35914ebd2f96793a533e3c5c5c80210e9b67766
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

<<<<<<< HEAD
=======
  config.include Capybara::DSL

  config.expect_with :rspec do |expectations|

    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end


  config.mock_with :rspec do |mocks|

    mocks.verify_partial_doubles = true
  end

>>>>>>> b35914ebd2f96793a533e3c5c5c80210e9b67766
end
